helm:
  parameters:
  - name: image.name
    value: ravitripathi/argocd
    forcestring: true
  - name: image.tag
    value: 1.0.1
    forcestring: true
  - name: nginx.image
    value: ravitripathi/argocd
    forcestring: true
  - name: nginx.tag
    value: 1.0.3
    forcestring: true
